### ISSUE TITLE
[Bug]: "The requested resource could not be found" on video upload And does not return video info on success

### ISSUE THREAD

**Issue by imsujan276** [apivideo/api.video-flutter-uploader#19]
### Version

1.2.3

### Environment that reproduces the issue

Device: Pixel 5 mobile and emulator
Flutter version: 3.22.1

### Is it reproducible in the example application?

Not tested

### Reproduction steps

- select a video
- upload it using "ApiVideoUploader.uploadWithUploadToken"

### Expected result

1. There should not be any error like that
2. On success, it should return video info

### Actual result

1.  on success, you see an error message in console "Error: PlatformException(java.lang.UnsupportedOperationException, Not Found: The requested resource could not be found., java.lang.UnsupportedOperationException: Not Found: The requested resource could not be found."
2. I do not get the uploaded video info

### Relevant logs output

```shell
Full error message:
[log] LOG => _uplaodVideoToAPiVideo() Error: PlatformException(java.lang.UnsupportedOperationException, Not Found: The requested resource could not be found., java.lang.UnsupportedOperationException: Not Found: The requested resource could not be found.
at video.api.flutter.uploader.UploaderModuleImpl$uploadPartAndObserve$4.invoke(UploaderModuleImpl.kt:346)
at video.api.flutter.uploader.UploaderModuleImpl$uploadPartAndObserve$4.invoke(UploaderModuleImpl.kt:333)
at video.api.flutter.uploader.utils.LiveDataExtensionsKt$observeTillItFinishes$4.onChanged(LiveDataExtensions.kt:36)
at video.api.flutter.uploader.utils.LiveDataExtensionsKt$observeTillItFinishes$4.onChanged(LiveDataExtensions.kt:20)
at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
, null)
```

**Comment by ThibaultBee** [comment]
Hi,

Your upload token might not be valid. Could you double check it?
See https://docs.api.video/reference/resource-not-found for reference.

**Comment by ThibaultBee** [comment]
From what I understand from your stack trace, your are trying to upload by part and not with `uploadWithUploadToken`. Could you provide the real code sample?

**Comment by imsujan276** [comment]
> Hi,
> 
> Your upload token might not be valid. Could you double check it? See https://docs.api.video/reference/resource-not-found for reference.

It is valid. I copied it from api.video dashboard and the selected video does gets uploaded to the videos section in api.video. It just does not return any response and shows that error in console

**Comment by imsujan276** [comment]
> From what I understand from your stack trace, your are trying to upload by part and not with `uploadWithUploadToken`. Could you provide the real code sample?

THis is the exact code i am using

**Comment by imsujan276** [comment]
> From what I understand from your stack trace, your are trying to upload by part and not with `uploadWithUploadToken`. Could you provide the real code sample?

Thank you @ThibaultBee, that error was on **.upload** and **.uploadPart** functions. 

But still

the "video info in return" issue is in the **.uploadWithUploadToken** too.

```
final video = await ApiVideoUploader.uploadWithUploadToken(
        'UPLOAD_TOKEN',
        pickedVideoPath,
        onProgress: (progress) {
          EasyLoad.progress(
            percentage: progress,
            message: 'Uploading ${(progress * 100)}%',
          );
        },
      );
 print(video)
 ```

**Comment by ThibaultBee** [comment]
About your first question, the reason is because the `videoId` you provide to `createProgressiveUploadSession` is incorrect. VideoId are given by api.video platform. 
To create a videoId, see https://docs.api.video/reference/api/Videos#create-a-video-object

Also, it is not secure to store an API key in an application, see https://docs.api.video/sdks/security
Using an upload token is a better practice but it should not be store in your app as you won't be able to renew if needed.

For your `uploadWithUploadToken` snippet, could you provide the exact stacktrace?

**Comment by imsujan276** [comment]
Here is the stacktrace for upload with token 

```
I/OpenGLRenderer(12078): Davey! duration=21895ms; Flags=1, FrameTimelineVsyncId=25294, IntendedVsync=14184051429411, Vsync=14184051429411, InputEventId=0, HandleInputStart=14184052154706, AnimationStart=14184052155378, PerformTraversalsStart=14184052155623, DrawStart=14184052476069, FrameDeadline=14184084762743, FrameInterval=14184052149916, FrameStartTime=16666666, SyncQueued=14184053850563, SyncStart=14184054098675, IssueDrawCommandsStart=14184055248219, SwapBuffers=14184066646980, FrameCompleted=14205947674899, DequeueBufferDuration=1163905, QueueBufferDuration=848550, GpuCompleted=14205947674899, SwapBuffersCompleted=14184074171773, DisplayPresentTime=4294967295, 
I/ExoPlayerImpl(12078): Init 39001dc [AndroidXMedia3/1.3.1] [emulator64_x86_64_arm64, sdk_gphone64_x86_64, Google, 31]
I/DMCodecAdapterFactory(12078): Creating an asynchronous MediaCodec adapter for track type video
I/Codec2Client(12078): Available Codec2 services: "default" "software"
I/CCodec  (12078): setting up 'default' as default (vendor) store
I/CCodec  (12078): Created component [c2.android.mpeg4.decoder]
I/CCodecConfig(12078): query failed after returning 9 values (BAD_INDEX)
I/MediaCodec(12078): MediaCodec will operate in async mode
I/MediaCodec(12078): [c2.android.mpeg4.decoder] setting surface generation to 12367873
I/CCodecConfig(12078): query failed after returning 9 values (BAD_INDEX)
I/CCodecBufferChannel(12078): [c2.android.mpeg4.decoder#812] Created output block pool with allocatorID 18 => poolID 60 - OK
I/DMABUFHEAPS(12078): Using DMA-BUF heap named: system
I/DMCodecAdapterFactory(12078): Creating an asynchronous MediaCodec adapter for track type audio
I/CCodec  (12078): setting up 'default' as default (vendor) store
I/CCodec  (12078): Created component [c2.android.aac.decoder]
I/CCodecConfig(12078): query failed after returning 19 values (BAD_INDEX)
I/MediaCodec(12078): MediaCodec will operate in async mode
I/CCodecConfig(12078): query failed after returning 19 values (BAD_INDEX)
I/CCodecBufferChannel(12078): [c2.android.aac.decoder#823] Created output block pool with allocatorID 16 => poolID 61 - OK
```

**Comment by ThibaultBee** [comment]
Have you set `videoId` parameter? Leave to `null` or don't set if you don't have a `videoId`.

**Comment by imsujan276** [comment]
When i dont set videoId, I dont get the error. still not getting the video response

Stacktrace:
```
I/OpenGLRenderer(12078): Davey! duration=326459ms; Flags=1, FrameTimelineVsyncId=26613, IntendedVsync=14304968091241, Vsync=14304968091241, InputEventId=127232446, HandleInputStart=14304969795673, AnimationStart=14304969796549, PerformTraversalsStart=14304969796855, DrawStart=14304995569777, FrameDeadline=14305001424573, FrameInterval=14304969770203, FrameStartTime=16666666, SyncQueued=14304995963994, SyncStart=14304996412770, IssueDrawCommandsStart=14304996545587, SwapBuffers=14304997319128, FrameCompleted=14631428487287, DequeueBufferDuration=2027509, QueueBufferDuration=741862, GpuCompleted=14631428487287, SwapBuffersCompleted=14305000684932, DisplayPresentTime=0, 
I/ExoPlayerImpl(12078): Init 9d896f8 [AndroidXMedia3/1.3.1] [emulator64_x86_64_arm64, sdk_gphone64_x86_64, Google, 31]
I/DMCodecAdapterFactory(12078): Creating an asynchronous MediaCodec adapter for track type video
I/CCodec  (12078): setting up 'default' as default (vendor) store
I/CCodec  (12078): Created component [c2.android.mpeg4.decoder]
I/CCodecConfig(12078): query failed after returning 9 values (BAD_INDEX)
I/MediaCodec(12078): MediaCodec will operate in async mode
I/MediaCodec(12078): [c2.android.mpeg4.decoder] setting surface generation to 12367876
I/CCodecConfig(12078): query failed after returning 9 values (BAD_INDEX)
I/CCodecBufferChannel(12078): [c2.android.mpeg4.decoder#115] Created output block pool with allocatorID 18 => poolID 66 - OK
I/DMCodecAdapterFactory(12078): Creating an asynchronous MediaCodec adapter for track type audio
I/CCodec  (12078): setting up 'default' as default (vendor) store
I/CCodec  (12078): Created component [c2.android.aac.decoder]
I/CCodecConfig(12078): query failed after returning 19 values (BAD_INDEX)
I/MediaCodec(12078): MediaCodec will operate in async mode
I/CCodecConfig(12078): query failed after returning 19 values (BAD_INDEX)
I/CCodecBufferChannel(12078): [c2.android.aac.decoder#227] Created output block pool with allocatorID 16 => poolID 67 - OK
I/WM-Processor(12078): Moving WorkSpec (2df38861-53f3-42e7-bac7-1ebe12c3d029) to the foreground
I/WM-SystemFgDispatcher(12078): Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.livevibe.apps.dev/androidx.work.impl.foreground.SystemForegroundService (has extras) }
I/WM-WorkerWrapper(12078): Worker result SUCCESS for Work [ id=2df38861-53f3-42e7-bac7-1ebe12c3d029, tags={ video.api.uploader.api.work.workers.UploadWorker, android-video-uploader, (token=to4OCXhjTB2lfrzqmF3swNih) } ]
I/WM-SystemFgDispatcher(12078): Stopping foreground service
```

**Comment by imsujan276** [comment]
Exact code i am using

```
void _uploadVideoToAPiVideo(String videoPath) async {
    try {

      final video = await ApiVideoUploader.uploadWithUploadToken(
        'UPLOAD_TOKEN',
        videoPath,
        onProgress: (progress) {
          EasyLoad.progress(
            percentage: progress,
            message: 'Uploading ${(progress * 100)}%',
          );
        },
      );
      log('LOG => _uplaodVideoToAPiVideo() Success: ${video.videoId} | ${video.assets?.mp4} | ${video.assets?.player}');
    } on Exception catch (e) {
      log('LOG => _uplaodVideoToAPiVideo() Exception: $e');
    } catch (e) {
      log('LOG => _uplaodVideoToAPiVideo() Error: $e');
    } finally {
      EasyLoad.dismiss();
    }
  }
  ```

**Comment by ThibaultBee** [comment]
Do you have anything after `I/WM-SystemFgDispatcher(12078): Stopping foreground service`?

Could you test on the provided example?

**Comment by imsujan276** [comment]
`Stopping foreground service` is the last line

**Comment by imsujan276** [comment]
the example seems to return the video object in response

**Comment by imsujan276** [comment]
when i use the same upload code inside my function `_uploadVideoToAPiVideo`, it does not print out the video

**Comment by ThibaultBee** [comment]
I put your code in the example. I get:
```
I/WM-SystemFgDispatcher(23622): Stopping foreground service
[log] LOG => _uplaodVideoToAPiVideo() Success: viXXXXX | https://vod.api.video/vod/viXXXXX/mp4/source.mp4 | https://embed.api.video/vod/viXXXXX
```
So it works.

**Comment by imsujan276** [comment]
let me check that again

**Comment by imsujan276** [comment]
even after removing the `EasyLoad` part, it does not seem to log the video info in my code

**Comment by ThibaultBee** [comment]
Is there something in your application that could unregister workmanager observer, live data or play for livecycle?

As it works with the example, there is definitely something in your application that changes the behavior of the uploader, thus it is almost impossible to assist you with this issue.
